### ISSUE TITLE
[Bug]: Taskflow输出为空或者报错。

### ISSUE THREAD

**Issue by xinliqingpi** [PaddlePaddle/PaddleNLP#6316] opened 2023-07-06 07:10 UTC
### 软件环境

```Markdown
- paddlepaddle:2.5.0
- paddlepaddle-gpu: 
- paddlenlp: 2.5.2
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
有时输出为空[{}],有时报一下错误
RuntimeError: (PreconditionNotMet) The meta data must be valid when call the mutable data function.
  [Hint: Expected valid() == true, but received valid():0 != true:1.] (at /paddle/paddle/phi/core/dense_tensor.cc:122)
  [operator < fill_constant > error]
```

### 稳定复现步骤 & 代码

from paddlenlp import Taskflow
from pprint import pprint

schema = ['情感倾向[正向，负向]']
senta = Taskflow("sentiment_analysis", model="uie-senta-base", schema=schema)
pprint(senta('蛋糕味道不错，店家服务也很好'))

**Comment by xinliqingpi** [comment] 2023-07-06 07:17
paddlepaddle:2.5.0 有bug 换成2.4.2就没问题。

**Comment by linjieccc** [comment] 2023-07-07 03:18
closing as duplicate of #6311

**Closed as completed by linjieccc** 2023-07-07 03:18 UTC
Labels: bug, triage
